name: ErfanGSI-build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Direct link to ROM'
        required: true
        default: 'https://cdnorg.d.miui.com/V14.0.4.0.TGCMIXM/miui_SPESGlobal_V14.0.4.0.TGCMIXM_69f8748327_13.0.zip'
      REPACK_NAME:
        description: 'Output filename'
        required: true
        default: 'output.7z'
      ROM_TYPE:
        description: 'ROM type (e.g., MIUI, Treble)'
        required: true
        default: 'MIUI'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          repository: tosasitill/erfanSGSI
          path: ErfanGSIs

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget gzip unzip curl axel aria2 zstd rename p7zip-full pigz liblzma-dev build-essential python3-dev android-sdk-libsparse-utils
          pip3 install aligo pycryptodome

      - name: Setup Tools
        run: |
          # Debug: Wo sind wir?
          pwd
          ls -F
          cd ErfanGSIs
          # Hier prüfen wir nochmal die Struktur
          ls -F
          sed -i 's/pycrypto//g' setup.sh
          sed -i 's/pip install/pip install --upgrade/g' setup.sh
          sudo bash setup.sh

      - name: Build GSI
        run: |
          cd ErfanGSIs
          sudo bash ./url2GSI.sh --ab ${{ github.event.inputs.ROM_URL }} ${{ github.event.inputs.ROM_TYPE }}

      - name: Compress and Upload
        run: |
          cd ErfanGSIs
          if [ -d "output" ] && [ "$(ls -A output/)" ]; then
            7za a -t7z -r ${{ github.event.inputs.REPACK_NAME }} output/*
          else
            echo "Error: Build failed or no files found."
            exit 1
          fi

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "ErfanGSIs/${{ github.event.inputs.REPACK_NAME }}"
          tag: "Build_${{ github.run_id }}"
          token: ${{ secrets.GITHUB_TOKEN }}
